services:

  vscode1:
    container_name: vscode-ssl-ssh
    hostname: vscode-ssl-ssh
    restart: always
    image: localhost/vscode-server-ssl-ssh 
    ports:
     - "8080:443"
    volumes:
     - '/opt/vscode-server/private:/etc/pki/nginx/private:Z'
     - '/opt/vscode-server/certs:/etc/pki/nginx:Z'
     - '/home/devops:/home/devops:Z'
