services:

  haproxy:
    container_name: haproxy
    hostname: haproxy
    restart: always
    image: localhost/haproxy
    ports:
     - "8443:8443"
    volumes:
     - '/srv/haproxy/etc/haproxy:/etc/haproxy:Z'
     - '/srv/haproxy/etc/ssl/certs:/etc/ssl/certs:Z'
